version: '3'
services:
  midjourney-proxy:
    container_name: midjourney-proxy
    network_mode: "host"
    image: registry.cn-hangzhou.aliyuncs.com/warape/midjourney-proxy:v1.0.0
    volumes:
      - /www/wwwroot/docker/midjourney-proxy/config:/home/spring/config  #config映射目录
      - /www/wwwroot/docker/midjourney-proxy/logs:/home/spring/logs     #logs映射目录
    environment:
      - JAVA_OPTS=-XX:MaxRAMPercentage=85 -Djava.awt.headless=true -XX:+HeapDumpOnOutOfMemoryError \
        -XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35 -Xlog:gc:file=/home/spring/logs/gc.log \
        -Dlogging.file.path=/home/spring/logs \
        -Dserver.port=8080 -Duser.timezone=Asia/Shanghai -Dfile.encoding=UTF-8 -Djava.rmi.server.hostname=midjourney-proxy
        - SPRING_CONFIG_LOCATION=file:/home/spring/config/
        - SERVER_PORT=8080 # 端口号 如果冲突可修改 修改后要和Nginx的反向代理做适配

